// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi1IQCQCYqEFW3uyOQhKa2x-_ZT4G7F8A',
    appId: '1:243745630044:web:52d40538e3fa4816698399',
    messagingSenderId: '243745630044',
    projectId: 'rootmie-vivero-a109c',
    authDomain: 'rootmie-vivero-a109c.firebaseapp.com',
    storageBucket: 'rootmie-vivero-a109c.firebasestorage.app',
    measurementId: 'G-R53XLW08BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhHVzGYPcTcg_Om27lCC2IVj5uipPtdpc',
    appId: '1:243745630044:android:4b3bbfc9e546ce8f698399',
    messagingSenderId: '243745630044',
    projectId: 'rootmie-vivero-a109c',
    storageBucket: 'rootmie-vivero-a109c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQQjZb6z_WIbqYv0ohNIOVO9L1kuS4yfU',
    appId: '1:243745630044:ios:88435248f412b542698399',
    messagingSenderId: '243745630044',
    projectId: 'rootmie-vivero-a109c',
    storageBucket: 'rootmie-vivero-a109c.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQQjZb6z_WIbqYv0ohNIOVO9L1kuS4yfU',
    appId: '1:243745630044:ios:88435248f412b542698399',
    messagingSenderId: '243745630044',
    projectId: 'rootmie-vivero-a109c',
    storageBucket: 'rootmie-vivero-a109c.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi1IQCQCYqEFW3uyOQhKa2x-_ZT4G7F8A',
    appId: '1:243745630044:web:4d19e103e77d491c698399',
    messagingSenderId: '243745630044',
    projectId: 'rootmie-vivero-a109c',
    authDomain: 'rootmie-vivero-a109c.firebaseapp.com',
    storageBucket: 'rootmie-vivero-a109c.firebasestorage.app',
    measurementId: 'G-LKWSCM5M9N',
  );
}
